### ISSUE TITLE
Prevent translation tests from running before semaphore table is available.

### ISSUE THREAD

**Issue by klonos** [backdrop/backdrop-issues#5943]
I can consistently reproduce this on my local, with the latest 1.x (reported as 1.25.x-dev), on php 8.0.26, but haven't been able to reproduce on a demo sandbox (still running core 1.23.1 on php 7.4.33).

1. Enable the "Testing" (simpletest) module
2. Head to `admin/config/development/testing` and try to run any test -> everything's OK 👍🏼 
3. Enable the "Language" module
4. Head to `admin/config/regional/language` and add any language
5. Head to `admin/config/development/testing` and try to run any test again -> error 👎🏼 

Full error:
```
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows.
Path: /batch?id=4&op=do_nojs&op=do StatusText: error ResponseText: PDOException:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdrop.simpletest804726semaphore'
doesn't exist: SELECT expire, value FROM {semaphore} WHERE name = :name;
Array ( [:name] => locale_cache_en ) in lock_may_be_available()
(line 166 of /app/docroot/core/includes/lock.inc).
Uncaught exception thrown in session handler.PDOException: SQLSTATE[42S02]:
Base table or view not found: 1146 Table &#039;backdrop.simpletest804726sessions&#039;
doesn&#039;t exist: UPDATE {sessions} SET `uid`=:db_update_placeholder_0,
`hostname`=:db_update_placeholder_1, `session`=:db_update_placeholder_2,
`timestamp`=:db_update_placeholder_3 WHERE ( (`sid` = :db_condition_placeholder_0) AND
(`ssid` = :db_condition_placeholder_1) ); Array ( [:db_update_placeholder_0] =&gt;
1 [:db_update_placeholder_1] =&gt; 172.20.0.2 [:db_update_placeholder_2] =&gt;
batches|a:2:{i:3;b:1;i:4;b:1;} [:db_update_placeholder_3] =&gt;
1674042925 [:db_condition_placeholder_0] =&gt; iDBpsz6yPGbe_RWx5E5XTTdHesdM70FMz4QFumuW1Ag
[:db_condition_placeholder_1] =&gt; iDBpsz6yPGbe_RWx5E5XTTdHesdM70FMz4QFumuW1Ag )
in _backdrop_session_write() (line 206 of /app/docroot/core/includes/session.inc).
Warning: Undefined array key 0 in /app/docroot/core/includes/errors.inc on line 282
Warning: Undefined array key "line" in
/app/docroot/core/modules/simpletest/backdrop_web_test_case.php on line 227
Warning: Undefined array key "file" in
/app/docroot/core/modules/simpletest/backdrop_web_test_case.php on line 228
Fatal error: Uncaught PDOException: SQLSTATE[23000]:
Integrity constraint violation: 1048 Column 'line' cannot be null in
/app/docroot/core/includes/database/database.inc:2285 Stack trace:
#0 /app/docroot/core/includes/database/database.inc(2285): PDOStatement->execute(Array)
#1 /app/docroot/core/includes/database/database.inc(717):
DatabaseStatementBase->execute(Array, Array)
#2 /app/docroot/core/includes/database/mysql/query.inc(34):
DatabaseConnection->query('INSERT INTO {si...', Array, Array)
#3 /app/docroot/core/modules/simpletest/backdrop_web_test_case.php(235):
InsertQuery_mysql->execute()
#4 /app/docroot/core/modules/simpletest/backdrop_web_test_case.php(533):
BackdropTestCase->assert('exception', 'Unknown: Failed...', 'Warning', Array)
#5 /app/docroot/core/modules/simpletest/backdrop_web_test_case.php(679):
BackdropTestCase->error('Unknown: Failed...', 'Warning', Array)
#6 [internal function]: BackdropTestCase->errorHandler(2, 'Unknown: Failed...', 'Unknown', 0)
#7 {main} thrown in /app/docroot/core/includes/database/database.inc on line 2285
```

**Comment by argiepiano** [comment]
I've seen this a few times when running tests in my local, after a test goes completely haywire  - something goes very wrong and the semphahore table that Backdrop creates for the testing environment is somehow removed and not created again when running the test again . Even after pressing "Clean environment", this thing still happened. The solution for me has been to completely uninstall Testing and reinstall it. But I never noticed any connection with Language.

Worth testing and looking into...

**Comment by argiepiano** [comment]
One more data point: I've been able to reproduce this crash consistently in my local if I enable Locale and run any test. 

Disabling Locale and clearing the testing environment seems to bring things back to normal with tests. So, while I haven't looked into the code, I think there are two things going on: 1. Locale has something that crashes the testing environment, and 2. Once it crashes, you start getting the semaphore error if you try running tests again, even after clearing the environment. 

Disabling Locale and clearing the environment gets the testing back on track for me.

So, definitely something going on with Locale. I'm testing with PHP 7.4

**Comment by indigoxela** [comment]
Yes, that's a known problem. At least, I know it. Wonder, why I didn't open an issue for this yet. (Possibly did?)

**Comment by klonos** [comment]
Thanks for taking the time to report back @argiepiano and @indigoxela 🙏🏼 

> The solution for me has been to completely uninstall Testing and reinstall it.

Tried that, but it didn't work in my case 🤔 

> ...I never noticed any connection with Language.

Yup, if I run the tests on vanilla, things work fine. Soon as I enable the Language module AND add a language, this starts happening. If I **disable** the Language module (no need to fully uninstall it), things start working again. So odd.

> I've been able to reproduce this crash consistently in my local if I enable Locale and run any test.

I've been trying to run `LanguageListTest` myself (troubleshooting a single remaining failure in the PR for #3422 if t matters).

> ...Wonder, why I didn't open an issue for this yet. (Possibly did?)

That's my thing, so here's an issue for you 😅 ...before opening this one, I tried searching the queue with various related terms, including `semaphore`. Nothing apparently related came up. ...now wondering if #4518 has anything to do with it 🤔

**Comment by klonos** [comment]
> ...now wondering if #4518 has anything to do with it 🤔 

What do you know?! ... @docwilmot in that issue suggested the following:

> Interesting. Could you add `require_once BACKDROP_ROOT . '/' . settings_get('lock_inc', 'core/includes/lock.inc');` to `install_begin_request()` (somewhere after  the line `backdrop_bootstrap(BACKDROP_BOOTSTRAP_CONFIGURATION);`) and recheck? 

And doing just that fixes the issue! 🎉  (for me at least)

**Comment by indigoxela** [comment]
I finally took the time to dig into this (as i18n module maintainer this is a real problem for me).

The problem is caused by _locale_get_config_translatables(), which has been introduced with translatable config.

`Issue #704: Add APIs for translating config strings.` https://github.com/backdrop/backdrop-issues/issues/704

To reproduce, it's only necessary to enable the locale module (no language needs to be added at all, just enable the module.

Any attempt to run a functional test on such a site will fail with a PDOException.

The functions are called in this order:

```
array (
  0 => 'lock_acquire',
  1 => 'locale',
  2 => '_locale_get_config_translatables',
  3 => 'locale_config_create',
  4 => 'module_invoke_all',
  5 => 'config_install_default_config',
  6 => 'setUp',
  7 => 'setUp',
  8 => 'setUp',
  9 => 'run',
  10 => '_simpletest_batch_operation',
  11 => '_batch_process',
  12 => '_batch_do',
  13 => '_batch_page',
  14 => 'system_batch_page',
  15 => 'menu_default_route_handler',
  16 => 'layout_route_handler',
  17 => 'menu_execute_active_handler',
)
```
The 'guilty' function code is:

https://github.com/backdrop/backdrop/blob/1.x/core/modules/locale/locale.module#L1073-L1079

**Comment by indigoxela** [comment]
Here's my proposed fix for the problem: https://github.com/backdrop/backdrop/pull/5021

I'm not sure, it this is the most elegant solution for a problem that only appears when running functional tests, but I didn't find a better place to do the safety check. It shouldn't be much overhead, though.

**How to test:**

- Enable the locale module (nothing else necessary)
- Enable the Testing module ("testing")
- Run some arbitrary tests

**Comment by argiepiano** [comment]
Hey @indigoxela, thanks for taking on this issue. Although I had been able to reproduce in the past, I'm having troubles now recreating the error. I enabled Locale, ran a test like `BlockTranslationTestCase`, but the test finished without issues. I then enabled Spanish, ran it again, nothing.

Anyway, I'm not sure why this is happening. Regardless of this, I was wondering why `semaphore` is not available - perhaps it hasn't yet been created in the testing environment? Do you have a sense if this is the case?

Also wondering if there may be a more standard solution, for example, trying to detect if we are in testing. I see some functions like `backdrop_system_listing()` check if they are in a testing environment by invoking `backdrop_valid_test_ua()`, which returns false if not in testing. This could be use in the if statement, perhaps? But maybe that wouldn't work in this case, if `_locale_get_config_translatables()` is indeed needed to run in any of the tests. I have no way to check this now that my tests are not failing 🙃

**Comment by indigoxela** [comment]
> I was wondering why semaphore is not available - perhaps it hasn't yet been created in the testing environment?

It hasn't been created *yet*. It's too early (setUp triggers config_install_default_config). But I was wondering if such "race conditions" might also happen in some D7 upgrades. No evidence for that, though.

>  I have no way to check this now that my tests are not failing 🙃

Yet another time it's unfortunate, that the tests are passing. 😆 

I'll try to give a  bit more info about my setup:

Apache + php-fpm (PHP 8.3 in the meantime, was the same with 7.4) + MariaDB 10.11. It's a "regular" server, no local dev environment, no docker or so involved. The server is usually fast.

Relevant modules enabled:

- language
- locale
- testing

Languages enabled: multiple, English is the default. (I forgot about that, as I had locale off for obvious reasons).
Language Detection and selection: nothing enabled.
Performance: all caching off
Simpletest settings: Cache installation profiles is off (for good reasons)

BlockTranslationTestCase - fails immediately with "Table 'bd_dev2.simpletestXXXXsemaphore' doesn't exist"
AdminBarDynamicLinksTestCase - fails immediately with "Table 'bd_dev2.simpletestXXXXsemaphore' doesn't exist"

And so on... not matter which test I try. As soon as I disable the locale module on that site, everything works. Note that only disabling already does the trick (no need to uninstall).

Note that enabling the profile cache makes things even worse for me (that's also not new, but unrelated here). Different PDOException.

@argiepiano does that give you any clue?

**Comment by indigoxela** [comment]
It's a bit unfortunate that this issue has stalled. But now at least I have a core patch to successfully run tests.

**Comment by laryn** [comment]
Thank you @indigoxela, @argiepiano, and @klonos. Merged into `1.x` and `1.31.x`.
